quitado el if

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -50,11 +50,11 @@ if [ ! -f $CACHE_FILE ]; then
   wget $IMAGE_MAGICK_URL -P $BUILD_DIR | indent
 
   echo "-----> Extracting ImageMagick from $BUILD_DIR/$IMAGE_MAGICK_FILE"
-  if [ ! -f $BUILD_DIR/$IMAGE_MAGICK_FILE ]; then
-    echo "Error: Unable to download ImageMagick" | indent
-    ls $BUILD_DIR | indent
-    exit 1;
-  fi
+  # if [ ! -f $BUILD_DIR/$IMAGE_MAGICK_FILE ]; then
+  #   echo "Error: Unable to extract ImageMagick" | indent
+  #   ls $BUILD_DIR | indent
+  #   exit 1;
+  # fi
   tar xvf $BUILD_DIR/$IMAGE_MAGICK_FILE | indent
 
   echo "-----> Building ImageMagick"
